
spring:
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    virtual-host: /
    port: 5672
    publisher-confirms: true
  application:
    name: rabbitmq-consumer-node2

server:
  port: 8086




