
spring:
# rabbitmq 配置
  rabbitmq:
#  用户名
    username: guest
#   密码
    password: guest
#    地址
    host: 127.0.0.1
#    虚拟空间地址
    virtual-host: /
#    端口号
    port: 5672
#    配置发布消息确认回调
    publisher-confirms: true

#    数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abc
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
